name: Create wheel

on:
  # run when a release has been created
  release:
    types: [created]
  # push:
  #   branches:
  #     - "go_wheel_*"

# env:
#   # comment TWINE_REPOSITORY_URL to use the real pypi. NOTE: change also the secret used in TWINE_PASSWORD
#   TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/

jobs:
  build_wheels:
    name: ${{ matrix.wheel_mode }} wheels ${{ matrix.python }} on ${{ matrix.os }} ${{ matrix.os == 'ubuntu-22.04' && matrix.linux_archs || '' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # emulated wheels on linux take too much time, split wheels into multiple runs
        python:
          - "cp310-*"
        wheel_mode:
          - 'pure-python'
        os:
          - "ubuntu-22.04"
        linux_archs:
          # this is only meaningful on linux. windows and macos ignore exclude all but one arch
          - "x86_64"

        include:
          # create pure python build
          - os: ubuntu-22.04
            wheel_mode: pure-python
            python: "cp-310*"

        exclude:
          - os: "windows-2022"
            linux_archs: "aarch64"
          - os: "macos-12"
            linux_archs: "aarch64"

      fail-fast: false

    steps:
      - uses: actions/checkout@v4


      - name: Set up Python for twine and pure-python wheel
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Build pure-python wheel
        if: ${{ matrix.wheel_mode == 'pure-python' && runner.os == 'Linux' }}
        run: |
          python -m pip install --upgrade pip
          pip --version
          pip install wheel
          pip list
          python setup.py bdist_wheel
          mkdir -p ./wheelhouse
          cp dist/*.whl  ./wheelhouse/

      # - uses: actions/upload-artifact@v3
      #   with:
      #     path: ./wheelhouse/*.whl

      - name: Upload wheels to release
        # upload the generated wheels to the github release
        uses: sqlalchemyorg/upload-release-assets@sa
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          files: './wheelhouse/*.whl'
