name: Create wheel

on:
  # run when a release has been created
  release:
    types: [created]
  workflow_dispatch:
  # push:
  #   branches:
  #     - "go_wheel_*"

# env:
#   # comment TWINE_REPOSITORY_URL to use the real pypi. NOTE: change also the secret used in TWINE_PASSWORD
#   TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/

jobs:
  build_wheels:
    name: "run_build"
    runs-on: "ubuntu-22.04"
     

    steps:
      - uses: actions/checkout@v4


      - name: Set up Python for twine and pure-python wheel
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Build pure-python wheel
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          pip --version
          pip install wheel build twine
          pip list
          python -m build
          python -m twine upload dist/* -u __token__ -p $PYPI_TOKEN
          mkdir -p ./wheelhouse
          cp dist/*  ./wheelhouse/

      # - uses: actions/upload-artifact@v3
      #   with:
      #     path: ./wheelhouse/*.whl

      - name: Upload wheels to release
        # upload the generated wheels to the github release
        uses: AButler/upload-release-assets@v3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          files: './wheelhouse/*'
